version: '3.9'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
    ports:
      - "3306:3306"
    restart: on-failure
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: on-failure
    networks:
      - mynetwork

  service-app:
    image: app-service
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - mynetwork

  query-app:
    image: app-query
    ports:
      - '8081:8081'
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - mynetwork

  socket-app:
    image: app-socket
    ports:
      - '8082:8082'
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - mynetwork

  auth-app:
    image: app-socket
    ports:
      - '8083:8083'
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - mynetwork

  front-app:
    image: inventory-front
    ports:
      - '4200:4200'
    restart: on-failure
    networks:
      - mynetwork



networks:
  mynetwork: