server:
  port: 8080
  ssl:
    enable: false
spring:
  application:
    name: "inventoryProject"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  r2dbc:
    url: "${MYSQL_URI:r2dbc:mysql://localhost:3306/inventory}"
    username: root
    password: root
  data:
    mongodb:
      uri: "${MONGO_URI:mongodb://localhost:27017/inventoryDB}"
  rabbitmq:
    host: toad-01.rmq.cloudamqp.com
    port: 5672
    username: rmruikcp
    password: 6-MMDMoEvOufr6up1zGut6wOeXnVit30
    virtual-host: rmruikcp

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowedOriginPatterns: "*"