server:
  port: 8083
  error:
    include-message: always
spring:
  application:
    name: "inventoryProject"
  devtools:
    add-properties: false
  r2dbc:
    url: "${MYSQL_URI:r2dbc:mysql://mysql-service:3306/inventory}"
    username: root
    password: root
  data:
    mongodb:
      uri: "${MONGO_URI:mongodb://mongodb-service:27017/inventoryDB}"
  rabbitmq:
    host: toad-01.rmq.cloudamqp.com
    port: 5672
    username: rmruikcp
    password: 6-MMDMoEvOufr6up1zGut6wOeXnVit30
    virtual-host: rmruikcp
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowedOriginPatterns: "*"
